<?php

/**
 * @file
 * Declare new panel layouts and styles to be used with the Demonstratie theme.
 */

/**
 * Implement hooks to template_preprocess and template_process the layouts.
 */
include_once('demonstratie_panels.preprocess.layouts.inc');
include_once('demonstratie_panels.process.layouts.inc');

/**
 * Implements hook_ctools_plugin_directory.
 */
function demonstratie_panels_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'panels') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_preprocess_panels_panel().
 */
function demonstratie_panels_preprocess_panels_pane(&$variables, $hook) {
  if (isset($variables['pane']->style['style']) && $variables['pane']->style['style'] == 'demonstratie_panels_styles') {

    if (isset($variables['settings']['title']) && $variables['settings']['title'] != 'default') {
      $variables['classes_array'][] = drupal_html_class($variables['settings']['title'] . '-title');
      $variables['title_attributes_array']['class'][] = drupal_html_class($variables['settings']['title'] . '-title-style');
      if ($variables['settings']['title'] == 'hidden') {
        $variables['title_attributes_array']['class'][] = 'element-invisible';
      }
    }

    if (isset($variables['settings']['hero']) && $variables['settings']['hero'] != 'default') {
      $variables['classes_array'][] = 'hero-image';
      $variables['classes_array'][] = 'demonstratie-hero-' . $variables['settings']['hero'];
    }

    if (isset($variables['settings']['layouts'])) {
      $variables['classes_array'][] = drupal_html_class($variables['settings']['layouts'] . '-layout');
    }

    if (isset($variables['settings']['styles'])) {
      $variables['classes_array'][] = drupal_html_class($variables['settings']['styles'] . '-style');
    }

    if (isset($variables['settings']['color_schemes'])) {
      $variables['classes_array'][] = drupal_html_class($variables['settings']['color_schemes'] . '-scheme');
    }

    if (isset($variables['settings']['button_styles'])) {
      $variables['classes_array'][] = drupal_html_class($variables['settings']['button_styles'] . '-button');
    }

    if (isset($variables['settings']['css_class'])) {
      $classes = explode(' ', $variables['settings']['css_class']);
      foreach ($classes as $class) {
        $variables['classes_array'][] = drupal_html_class($class);
      }
    }

    $variables['classes_array'][] = 'clearfix';
  }
}
