<?php
include_once('includes/panels_preview.add.inc');
include_once('includes/panels_preview.edit.inc');

/**
 * The default list of view modes to exclude from pane configuration forms.
 */
define('PANELS_PREVIEW_HIDDEN_VIEW_MODE_OPTIONS', "rss\nsearch_index\nsearch_result\ntoken\npreview\ndiff_standard");

/**
 * Implements hook_module_implements_alter()
 */
function panels_preview_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter' && isset($implementations['panels_preview'])) {
    $group = $implementations['panels_preview'];
    unset($implementations['panels_preview']);
    $implementations['panels_preview'] = $group;
  }
}
