<?php

/**
 * Implements hook_modules_enabled().
 *
 * When any module is enabled, process any corresponding migrations.
 */
function sbp_migrate_modules_enabled($modules) {
  migrate_static_registration();
  sbp_migrate_enable_migrate_support();
  sbp_migrate_process_imports($modules);
}

/**
 * Implements hook_module_implements_alter().
 *
 * Move our hook_modules_enabled() implementation to after that of Features so
 * that fields are created in time to migrate into them.
 */
function sbp_migrate_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'modules_enabled') {
    $group = $implementations['sbp_migrate'];
    unset($implementations['sbp_migrate']);
    $implementations['sbp_migrate'] = $group;
  }
}

/**
 * Implements hook_migrate_api().
 */
function sbp_migrate_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(),
    'groups' => array(
      'sbp' => array(
        'title' => t('Business Portal'),
      ),
    ),
    'field handlers' => array(
      'SBPMigrateTaxonomyTermReferenceFieldHandler',
    ),
  );

  $map = sbp_migrate_map();

  foreach ($map as $class_name => $module_name) {
    $api['migrations'][$class_name] = array(
      'class_name' => $class_name,
      'group_name' => 'sbp',
    );
  }
  return $api;
}

/**
 * Return an array of migrate classes and corresponding modules, limited to
 * currently enabled modules.
 */
function sbp_migrate_map() {
  $map = array(
    'SBPMigrationTermDepartmentType' => 'sbp_taxonomy',
    'SBPMigrationTermBusinessNeeds' => 'sbp_taxonomy',
    'SBPMigrationTermBusinessOwnership' => 'sbp_taxonomy',
    'SBPMigrationTermIndustryTags' => 'sbp_taxonomy',
    'SBPMigrationTermResourceType' => 'sbp_taxonomy',
    'SBPMigrationTermTermsDefinitionsGrouping' => 'sbp_taxonomy',
    'SBPMigrationTermTermsDefinitions' => 'sbp_taxonomy',
    'SBPMigrationTermBusinessPortalWizardSections' => 'sbp_taxonomy',
    'SBPMigrationNodeLandingPage' => 'sbp_landing_page',
    'SBPMigrationNodeBusinessSponsor' => 'sbp_business_sponsors',
    'SBPMigrationNodeIncentives' => 'sbp_incentives',
    'SBPMigrationNodeOnlineResources' => 'sbp_online_resources',
    'SBPMigrationNodeStarterKit' => 'sbp_starter_kit',
    'SBPMigrationNodeDepartment' => 'sbp_department',
    'SBPMigrationNodeWizardScreen' => 'sbp_wizard_screen',
    'SBPMigrationFieldCollectionStarterKitChecklistItems' => 'sbp_field_collection_starter_kit_checklist_items',
    'SBPMigrationFieldCollectionStarterKitPermitSection' => 'sbp_field_collection_starter_kit_permit_section',
    'SBPMigrationFieldCollectionDepartmentAddresses' => 'sbp_field_collection_department_addresses',
    'SBPMigrationFieldCollectionWizardScreenButton' => 'sbp_field_collection_wizard_screen_button',
    'SBPMigrationTermStyleTemplate' => 'sbp_taxonomy',
    'SBPMigrationFieldCollectionOnlineResourcesHero' => 'sbp_field_collection_online_resources_hero',
    'SBPMigrationFieldCollectionIncentivesHero' => 'sbp_field_collection_incentives_hero',
    'SBPMigrationFieldCollectionStarterKitHero' => 'sbp_field_collection_starter_kit_hero',
    'SBPMigrationFieldCollectionDepartmentHero' => 'sbp_field_collection_department_hero',
    'SBPMigrationFieldCollectionLandingPageHero' => 'sbp_field_collection_landing_page_hero',
    'SBPMigrationFPPFourColumnCTA' => 'sbp_fpp_four_column_cta',
    'SBPMigrationFPPThreeColumnCTA' => 'sbp_fpp_three_column_cta',
    'SBPMigrationFPPGeneralContent' => 'sbp_fpp_general_content',
    'SBPMigrationFPPSectionContent' => 'sbp_fpp_section_content',
    'SBPMigrationFPPPullQuote' => 'sbp_fpp_pull_quote',
    'SBPMigrationFPPTimeline' => 'sbp_fpp_timeline',
    'SBPMigrationFPPFeaturedResources' => 'sbp_fpp_featured_resources',
    'SBPMigrationFPPFieldCollectionFourColumnCTACallsToActions' => 'sbp_fpp_field_collection_four_column_cta_calls_to_actions',
    'SBPMigrationFPPFieldCollectionThreeColumnCTAThreeCTAS' => 'sbp_fpp_field_collection_three_column_cta_three_ctas',
    'SBPMigrationFPPFieldCollectionTimelineTimelineItems' => 'sbp_fpp_field_collection_timeline_timeline_items',
  );
  // Allow other modules to alter the migrations to, for example, use
  // a custom class.
  drupal_alter('sbp_migrate_map', $map);
  // Only add a class if its corresponding module is enabled.
  return $map;
  //return array_filter($map, 'module_exists');
}

/**
 * Enable required custom migrate support modules.
 */
function sbp_migrate_enable_migrate_support($modules = array()) {
  // Ensure that migration classes are registered.
  migrate_get_module_apis(TRUE);
  $map = sbp_migrate_map();
  if (!empty($modules)) {
    $map = array_intersect($map, $modules);
  }
  $map = array_filter($map, 'module_exists');
  if (!empty($map)) {
    module_enable(array_keys($map));
  }
}

/**
 * Process all registered migrations or those of a specified set of modules.
 */
function sbp_migrate_process_imports($modules = array()) {
  // Ensure that migration classes are registered.
  migrate_get_module_apis(TRUE);

  $migration_order = array();
  $migration_order[0] = 'SBPMigrationTermDepartmentType';
  $migration_order[1] = 'SBPMigrationTermBusinessNeeds';
  $migration_order[2] = 'SBPMigrationTermBusinessOwnership';
  $migration_order[3] = 'SBPMigrationTermIndustryTags';
  $migration_order[4] = 'SBPMigrationTermResourceType';
  $migration_order[5] = 'SBPMigrationTermTermsDefinitionsGrouping';
  $migration_order[6] = 'SBPMigrationTermTermsDefinitions';
  $migration_order[7] = 'SBPMigrationTermBusinessPortalWizardSections';
  $migration_order[9] = 'SBPMigrationNodeLandingPage';
  $migration_order[10] = 'SBPMigrationNodeDepartment';
  $migration_order[11] = 'SBPMigrationNodeBusinessSponsor';
  $migration_order[12] = 'SBPMigrationNodeIncentives';
  $migration_order[13] = 'SBPMigrationNodeOnlineResources';
  $migration_order[14] = 'SBPMigrationNodeStarterKit';
  $migration_order[15] = 'SBPMigrationNodeWizardScreen';
  $migration_order[16] = 'SBPMigrationFieldCollectionStarterKitChecklistItems';
  $migration_order[17] = 'SBPMigrationFieldCollectionStarterKitPermitSection';
  $migration_order[18] = 'SBPMigrationFieldCollectionDepartmentAddresses';
  $migration_order[19] = 'SBPMigrationFieldCollectionWizardScreenButton';
  $migration_order[20] = 'SBPMigrationTermStyleTemplate';
  $migration_order[21] = 'SBPMigrationFieldCollectionOnlineResourcesHero';
  $migration_order[22] = 'SBPMigrationFieldCollectionIncentivesHero';
  $migration_order[23] = 'SBPMigrationFieldCollectionStarterKitHero';
  $migration_order[24] = 'SBPMigrationFieldCollectionDepartmentHero';
  $migration_order[25] = 'SBPMigrationFieldCollectionLandingPageHero';
  $migration_order[26] = 'SBPMigrationFPPFourColumnCTA';
  $migration_order[27] = 'SBPMigrationFPPThreeColumnCTA';
  $migration_order[28] = 'SBPMigrationFPPGeneralContent';
  $migration_order[29] = 'SBPMigrationFPPSectionContent';
  $migration_order[30] = 'SBPMigrationFPPPullQuote';
  $migration_order[31] = 'SBPMigrationFPPTimeline';
  $migration_order[32] = 'SBPMigrationFPPFeaturedResources';
  $migration_order[33] = 'SBPMigrationFPPFieldCollectionFourColumnCTACallsToActions';
  $migration_order[34] = 'SBPMigrationFPPFieldCollectionThreeColumnCTAThreeCTAS';
  $migration_order[35] = 'SBPMigrationFPPFieldCollectionTimelineTimelineItems';


  $map = sbp_migrate_map();
  if (!empty($modules)) {
    $map = array_intersect($map, $modules);
  }

  echo 'Here is the parade of migration classes as they migrate:';
  foreach ($migration_order as $class_name) {
    foreach (array_keys($map) as $key)
    if ($key == $class_name) {
      $migration = Migration::getInstance($class_name);
      $migration->processImport();
      echo ' ' . $class_name . ' ';
    }
  }
}
