source 'https://rubygems.org'

group :frontend do
  gem 'compass',        '<= 1.0.3'
  # Build compass sprites faster with oily_png.
  gem 'oily_png',       '~> 1.1'
  gem 'sass',           '~> 3.3'
  gem 'sass-globbing',  '~> 1.1'
  gem 'zen-grids',      '~> 1.5'
end
