language: php
sudo: false

php:
  - 5.3
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

addons:
  apt:
    packages:
      - php5-cgi
      - php5-mysql

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:6.*

before_script:
  - form_builder=`pwd`
  - cd ..
  - git clone https://github.com/torotil/upal.git
  - upal=`pwd`/upal
  - mysql -e 'create database drupal'
  - php -d sendmail_path=`which true` ~/.composer/vendor/bin/drush.php --yes core-quick-drupal --profile=testing --no-server --db-url=mysql://root:@127.0.0.1/drupal --enable=simpletest form_builder_test
  - ln -s $form_builder form_builder_test/drupal/sites/all/modules/form_builder
  - cd form_builder_test/drupal
  - root=`pwd`
  - drush dl webform-7.x-3.x ctools options_element
  - drush --yes pm-enable form_builder_webform form_builder_examples

script:
  - cd $form_builder
  - UPAL_ROOT=$root UPAL_DB_URL=mysql://root:@127.0.0.1/drupal UPAL_WEB_URL=http://127.0.0.1 phpunit -c phpunit.xml --bootstrap $upal/bootstrap.php $form_builder/tests
